-- Wrap auth.uid()/current_setting() in RLS policy predicates in (select ...) so
-- Postgres evaluates each once per statement (an InitPlan) instead of once per row --
-- the Supabase-documented RLS perf pattern. Covers USING and WITH CHECK. Predicate-
-- equivalent (row visibility unchanged). Generated by 'pgrls fix --rule PERF001'
-- (pgrls 0.44.0) and verified on Postgres 16 (PERF001 -> 0).

-- [PERF001] Wrap auth function call(s) in policy 'activity_logs_team_insert' on public.activity_logs so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY activity_logs_team_insert ON public.activity_logs
    WITH CHECK (project_id IN (SELECT projects.id FROM projects WHERE projects.user_id = auth.uid()) OR project_id IN (SELECT user_accessible_projects.project_id FROM user_accessible_projects WHERE user_accessible_projects.accessor_id = auth.uid()) OR user_has_direct_project_access(project_id, (SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'activity_logs_team_select' on public.activity_logs so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY activity_logs_team_select ON public.activity_logs
    USING (project_id IN (SELECT projects.id FROM projects WHERE projects.user_id = auth.uid()) OR project_id IN (SELECT user_accessible_projects.project_id FROM user_accessible_projects WHERE user_accessible_projects.accessor_id = auth.uid()) OR user_has_direct_project_access(project_id, (SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'columns_team_insert' on public.columns so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY columns_team_insert ON public.columns
    WITH CHECK (project_id IN (SELECT projects.id FROM projects WHERE projects.user_id = auth.uid()) OR project_id IN (SELECT user_accessible_projects.project_id FROM user_accessible_projects WHERE user_accessible_projects.accessor_id = auth.uid()) OR user_has_direct_project_access(project_id, (SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'columns_team_select' on public.columns so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY columns_team_select ON public.columns
    USING (project_id IN (SELECT projects.id FROM projects WHERE projects.user_id = auth.uid()) OR project_id IN (SELECT user_accessible_projects.project_id FROM user_accessible_projects WHERE user_accessible_projects.accessor_id = auth.uid()) OR user_has_direct_project_access(project_id, (SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'columns_team_update' on public.columns so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY columns_team_update ON public.columns
    USING (project_id IN (SELECT projects.id FROM projects WHERE projects.user_id = auth.uid()) OR project_id IN (SELECT user_accessible_projects.project_id FROM user_accessible_projects WHERE user_accessible_projects.accessor_id = auth.uid()) OR user_has_direct_project_access(project_id, (SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'notifications_delete_own' on public.notifications so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY notifications_delete_own ON public.notifications
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'notifications_select_own' on public.notifications so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY notifications_select_own ON public.notifications
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'notifications_update_own' on public.notifications so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY notifications_update_own ON public.notifications
    USING (user_id = (SELECT auth.uid()))
    WITH CHECK (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'profiles_insert_own' on public.profiles so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY profiles_insert_own ON public.profiles
    WITH CHECK ((SELECT auth.uid()) = id);

-- [PERF001] Wrap auth function call(s) in policy 'profiles_update_own' on public.profiles so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY profiles_update_own ON public.profiles
    USING ((SELECT auth.uid()) = id)
    WITH CHECK ((SELECT auth.uid()) = id);

-- [PERF001] Wrap auth function call(s) in policy 'secure_profiles_insert_own' on public.profiles so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY secure_profiles_insert_own ON public.profiles
    WITH CHECK ((SELECT auth.uid()) = id);

-- [PERF001] Wrap auth function call(s) in policy 'secure_profiles_select_others_basic' on public.profiles so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY secure_profiles_select_others_basic ON public.profiles
    USING ((SELECT auth.uid()) IS NOT NULL AND (SELECT auth.uid()) <> id);

-- [PERF001] Wrap auth function call(s) in policy 'secure_profiles_select_own' on public.profiles so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY secure_profiles_select_own ON public.profiles
    USING ((SELECT auth.uid()) = id);

-- [PERF001] Wrap auth function call(s) in policy 'secure_profiles_update_own' on public.profiles so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY secure_profiles_update_own ON public.profiles
    USING ((SELECT auth.uid()) = id)
    WITH CHECK ((SELECT auth.uid()) = id);

-- [PERF001] Wrap auth function call(s) in policy 'project_members_team_select' on public.project_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY project_members_team_select ON public.project_members
    USING (project_id IN (SELECT projects.id FROM projects WHERE projects.user_id = auth.uid()) OR project_id IN (SELECT user_accessible_projects.project_id FROM user_accessible_projects WHERE user_accessible_projects.accessor_id = auth.uid()) OR user_id = (SELECT auth.uid()) OR user_has_direct_project_access(project_id, (SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'projects_accessible' on public.projects so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY projects_accessible ON public.projects
    USING (user_id = (SELECT auth.uid()) OR id IN (SELECT user_accessible_projects.project_id FROM user_accessible_projects WHERE user_accessible_projects.accessor_id = auth.uid()) OR user_has_direct_project_access(id, (SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'projects_owner_delete' on public.projects so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY projects_owner_delete ON public.projects
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'projects_owner_modify' on public.projects so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY projects_owner_modify ON public.projects
    WITH CHECK (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'projects_owner_update' on public.projects so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY projects_owner_update ON public.projects
    USING (user_id = (SELECT auth.uid()))
    WITH CHECK (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'task_comments_own_delete' on public.task_comments so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY task_comments_own_delete ON public.task_comments
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'task_comments_own_update' on public.task_comments so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY task_comments_own_update ON public.task_comments
    USING (user_id = (SELECT auth.uid()))
    WITH CHECK (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'task_comments_team_insert' on public.task_comments so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY task_comments_team_insert ON public.task_comments
    WITH CHECK (task_id IN (SELECT t.id FROM tasks AS t INNER JOIN columns AS c ON c.id = t.column_id WHERE c.project_id IN (SELECT projects.id FROM projects WHERE projects.user_id = auth.uid()) OR c.project_id IN (SELECT user_accessible_projects.project_id FROM user_accessible_projects WHERE user_accessible_projects.accessor_id = auth.uid()) OR user_has_direct_project_access(c.project_id, auth.uid())) AND user_id = (SELECT auth.uid()));
